name: Run Cypress Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm ci

            - name: Create .env file
              run: |
                  echo "BASE_URL='${{ secrets.BASE_URL }}'" >> .env
                  echo "STANDARD_USERNAME='${{ secrets.STANDARD_USERNAME }}'" >> .env
                  echo "STANDARD_PASSWORD='${{ secrets.STANDARD_PASSWORD }}'" >> .env
                  echo "FASILITAS='${{ secrets.FASILITAS }}'" >> .env
                  echo "DESKRIPSI='${{ secrets.DESKRIPSI }}'" >> .env
                  echo "DATE='${{ secrets.DATE }}'" >> .env

            - name: Run Cypress Tests
              run: npx cypress run
